#include "note_def.h"
#include "fixed.h"
#include "gfx.h"
#include "stage.h"
#include "pad.h"

//4K
int note_x4k_normal[8] = {
	// BF - normal
	FIXED_DEC(26,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(60,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC(94,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(128,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - normal
	FIXED_DEC(-128,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-94,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC(-60,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x4k_flipped[8] = {
	// BF - flipped (on left side, like 5k)
	FIXED_DEC(-128,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-94,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-60,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - flipped (on right side, like 5k)
	FIXED_DEC(26,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(60,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(94,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(128,1) + FIXED_DEC(SCREEN_WIDEADD,4),
};

//5K
int note_x5k_normal[10] = {
	// BF - normal
	FIXED_DEC(16-10,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(50-10,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC(84-10,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(118-10,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(150-10,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - normal
	FIXED_DEC(-128-10,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-94-10,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC(-512,1)    - FIXED_DEC(SCREEN_WIDEADD,4),// special case
	FIXED_DEC(-60-10,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26-10,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x5k_flipped[10] = {
	//BF
	 FIXED_DEC(-150 + 10,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	 FIXED_DEC(-118 + 10,1) - FIXED_DEC(SCREEN_WIDEADD,4),//+34
	 FIXED_DEC(-84 + 10,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	 FIXED_DEC(-50 + 10,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	 FIXED_DEC(-16 + 10,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	//Opponent
	 FIXED_DEC(26 + 10,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	 FIXED_DEC(60 + 10,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+34
	 FIXED_DEC(512,1) + FIXED_DEC(SCREEN_WIDEADD,4),//+34
	 FIXED_DEC(94 + 10,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	 FIXED_DEC(128 + 10,1) + FIXED_DEC(SCREEN_WIDEADD,4),
};

//6K
int note_x6k_normal[12] = {
	// BF - normal
	FIXED_DEC(26,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(50,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+24
	FIXED_DEC(74,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(98,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(122,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(146,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - normal
	FIXED_DEC(-146,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-122,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-98,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-74,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+24
	FIXED_DEC(-50,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x6k_flipped[12] = {
	// BF - flipped (on left side, like 5k)
	FIXED_DEC(-146,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-122,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-98,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-74,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-50,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - flipped (on right side, like 5k)
	FIXED_DEC(26,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(50,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(74,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(98,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(122,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(146,1) + FIXED_DEC(SCREEN_WIDEADD,4),
};

//7K
int note_x7k_normal[14] = {
	// BF - normal
	FIXED_DEC(26,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(46,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+20
	FIXED_DEC(66,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(106,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(126,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(146,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - normal
	FIXED_DEC(-146,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-126,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-106,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-86,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-66,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+20
	FIXED_DEC(-48,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x7k_flipped[14] = {
	// BF - flipped (on left side, like 5k)
	FIXED_DEC(-146,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-126,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-106,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-86,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-66,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-48,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - flipped (on right side, like 5k)
	FIXED_DEC(26,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(46,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(66,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(106,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(126,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(146,1) + FIXED_DEC(SCREEN_WIDEADD,4),
};

//9K
int note_x9k_normal[18] = {
	// BF - normal
	FIXED_DEC(13,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(30,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+17
	FIXED_DEC(47,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(64,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(81,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(98,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(115,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(132,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(149,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - normal
	FIXED_DEC(-149,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-132,1) - FIXED_DEC(SCREEN_WIDEADD,4),//+17
	FIXED_DEC(-115,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-98,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-81,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-64,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-47,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-30,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-13,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x9k_flipped[18] = {
	// BF - flipped (on left side, like 5k)
	FIXED_DEC(-149,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-132,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-115,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-98,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-81,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-64,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-47,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-30,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-13,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent - flipped (on right side, like 5k)
	FIXED_DEC(13,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(30,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(47,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(64,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(81,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(98,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(115,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(132,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(149,1) + FIXED_DEC(SCREEN_WIDEADD,4),
};

// Rotten Smoothie middle (centered BF)
int note_x4k_rotten_smoothie_middle[8] = {
	// BF
	FIXED_DEC(26-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(60-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC(94-52,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(128-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent
	FIXED_DEC(-128,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-94,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC(-60,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x5k_rotten_smoothie_middle[10] = {
	// BF
	FIXED_DEC((16-10)-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC((50-10)-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC((84-10)-64,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC((118-10)-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC((150-10)-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent
	FIXED_DEC(-128-10,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-94-10,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+34
	FIXED_DEC(-512,1)    - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-60-10,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26-10,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x6k_rotten_smoothie_middle[12] = {
	// BF
	FIXED_DEC(26-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(50-84,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+24
	FIXED_DEC(74-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(98-52,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(122-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(146-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent
	FIXED_DEC(-146,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-122,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-98,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-74,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+24
	FIXED_DEC(-50,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x7k_rotten_smoothie_middle[14] = {
	// BF
	FIXED_DEC(26-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(46-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+20
	FIXED_DEC(66-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(86-64,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(106-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(126-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(146-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent
	FIXED_DEC(-146,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-126,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-106,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-86,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-66,1)  - FIXED_DEC(SCREEN_WIDEADD,4),//+20
	FIXED_DEC(-46,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-26,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

int note_x9k_rotten_smoothie_middle[18] = {
	// BF
	FIXED_DEC(13-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(30-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),//+17
	FIXED_DEC(47-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(64-86,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(81-64,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(98-52,1)  + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(115-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(132-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(149-52,1) + FIXED_DEC(SCREEN_WIDEADD,4),
	// Opponent
	FIXED_DEC(-149,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-132,1) - FIXED_DEC(SCREEN_WIDEADD,4),//+17
	FIXED_DEC(-115,1) - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-98,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-81,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-64,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-47,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-30,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
	FIXED_DEC(-13,1)  - FIXED_DEC(SCREEN_WIDEADD,4),
};

u16 note_key4k[] = {INPUT_LEFT, INPUT_DOWN, INPUT_UP, INPUT_RIGHT};
u8 note_anims4k[4][3] = {
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Down,  CharAnim_DownAlt,  PlayerAnim_DownMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
};

u16 note_key5k[] = {INPUT_LEFT5K, INPUT_DOWN5K, INPUT_MIDDLE, INPUT_UP5K, INPUT_RIGHT5K};
u8 note_anims5k[5][3] = {
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Down,  CharAnim_DownAlt,  PlayerAnim_DownMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
};

u16 note_key6k[] = {PAD_LEFT, PAD_UP, PAD_RIGHT, PAD_SQUARE, PAD_CROSS, PAD_CIRCLE};
u8 note_anims6k[6][3] = {
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Down,  CharAnim_DownAlt,  PlayerAnim_DownMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
};

u16 note_key7k[] = {PAD_LEFT, PAD_UP, PAD_RIGHT, INPUT_MIDDLE, PAD_SQUARE, PAD_CROSS, PAD_CIRCLE};
u8 note_anims7k[7][3] = {
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Down,  CharAnim_DownAlt,  PlayerAnim_DownMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
};

u16 note_key9k[] = {PAD_LEFT, PAD_DOWN, PAD_UP, PAD_RIGHT, INPUT_MIDDLE, PAD_SQUARE, PAD_CROSS, PAD_TRIANGLE, PAD_CIRCLE};
u8 note_anims9k[9][3] = {
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Down,  CharAnim_DownAlt,  PlayerAnim_DownMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Left,  CharAnim_LeftAlt,  PlayerAnim_LeftMiss},
	{CharAnim_Down,  CharAnim_DownAlt,  PlayerAnim_DownMiss},
	{CharAnim_Up,    CharAnim_UpAlt,    PlayerAnim_UpMiss},
	{CharAnim_Right, CharAnim_RightAlt, PlayerAnim_RightMiss},
};
